// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/clients/ldap/client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ldap "github.com/go-ldap/ldap/v3"
	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/redhat-data-and-ai/usernaut/api/v1alpha1"
)

// MockLDAPConnClient is a mock of LDAPConnClient interface.
type MockLDAPConnClient struct {
	ctrl     *gomock.Controller
	recorder *MockLDAPConnClientMockRecorder
}

// MockLDAPConnClientMockRecorder is the mock recorder for MockLDAPConnClient.
type MockLDAPConnClientMockRecorder struct {
	mock *MockLDAPConnClient
}

// NewMockLDAPConnClient creates a new mock instance.
func NewMockLDAPConnClient(ctrl *gomock.Controller) *MockLDAPConnClient {
	mock := &MockLDAPConnClient{ctrl: ctrl}
	mock.recorder = &MockLDAPConnClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLDAPConnClient) EXPECT() *MockLDAPConnClientMockRecorder {
	return m.recorder
}

// IsClosing mocks base method.
func (m *MockLDAPConnClient) IsClosing() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClosing")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsClosing indicates an expected call of IsClosing.
func (mr *MockLDAPConnClientMockRecorder) IsClosing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClosing", reflect.TypeOf((*MockLDAPConnClient)(nil).IsClosing))
}

// Search mocks base method.
func (m *MockLDAPConnClient) Search(arg0 *ldap.SearchRequest) (*ldap.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0)
	ret0, _ := ret[0].(*ldap.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockLDAPConnClientMockRecorder) Search(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockLDAPConnClient)(nil).Search), arg0)
}

// UnauthenticatedBind mocks base method.
func (m *MockLDAPConnClient) UnauthenticatedBind(username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnauthenticatedBind", username)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnauthenticatedBind indicates an expected call of UnauthenticatedBind.
func (mr *MockLDAPConnClientMockRecorder) UnauthenticatedBind(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnauthenticatedBind", reflect.TypeOf((*MockLDAPConnClient)(nil).UnauthenticatedBind), username)
}

// MockLDAPClient is a mock of LDAPClient interface.
type MockLDAPClient struct {
	ctrl     *gomock.Controller
	recorder *MockLDAPClientMockRecorder
}

// MockLDAPClientMockRecorder is the mock recorder for MockLDAPClient.
type MockLDAPClientMockRecorder struct {
	mock *MockLDAPClient
}

// NewMockLDAPClient creates a new mock instance.
func NewMockLDAPClient(ctrl *gomock.Controller) *MockLDAPClient {
	mock := &MockLDAPClient{ctrl: ctrl}
	mock.recorder = &MockLDAPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLDAPClient) EXPECT() *MockLDAPClientMockRecorder {
	return m.recorder
}

// BuildLDAPQueryFromSpec mocks base method.
func (m *MockLDAPClient) BuildLDAPQueryFromSpec(ctx context.Context, query *v1alpha1.LDAPQuery) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildLDAPQueryFromSpec", ctx, query)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildLDAPQueryFromSpec indicates an expected call of BuildLDAPQueryFromSpec.
func (mr *MockLDAPClientMockRecorder) BuildLDAPQueryFromSpec(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildLDAPQueryFromSpec", reflect.TypeOf((*MockLDAPClient)(nil).BuildLDAPQueryFromSpec), ctx, query)
}

// GetBulkUserLDAPData mocks base method.
func (m *MockLDAPClient) GetBulkUserLDAPData(ctx context.Context, userIDs []string) (map[string]map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBulkUserLDAPData", ctx, userIDs)
	ret0, _ := ret[0].(map[string]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBulkUserLDAPData indicates an expected call of GetBulkUserLDAPData.
func (mr *MockLDAPClientMockRecorder) GetBulkUserLDAPData(ctx, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBulkUserLDAPData", reflect.TypeOf((*MockLDAPClient)(nil).GetBulkUserLDAPData), ctx, userIDs)
}

// GetQueryMembers mocks base method.
func (m *MockLDAPClient) GetQueryMembers(ctx context.Context, query string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryMembers", ctx, query)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueryMembers indicates an expected call of GetQueryMembers.
func (mr *MockLDAPClientMockRecorder) GetQueryMembers(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryMembers", reflect.TypeOf((*MockLDAPClient)(nil).GetQueryMembers), ctx, query)
}

// GetUserLDAPData mocks base method.
func (m *MockLDAPClient) GetUserLDAPData(ctx context.Context, userID string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserLDAPData", ctx, userID)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLDAPData indicates an expected call of GetUserLDAPData.
func (mr *MockLDAPClientMockRecorder) GetUserLDAPData(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLDAPData", reflect.TypeOf((*MockLDAPClient)(nil).GetUserLDAPData), ctx, userID)
}

// GetUserLDAPDataByEmail mocks base method.
func (m *MockLDAPClient) GetUserLDAPDataByEmail(ctx context.Context, email string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserLDAPDataByEmail", ctx, email)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLDAPDataByEmail indicates an expected call of GetUserLDAPDataByEmail.
func (mr *MockLDAPClientMockRecorder) GetUserLDAPDataByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLDAPDataByEmail", reflect.TypeOf((*MockLDAPClient)(nil).GetUserLDAPDataByEmail), ctx, email)
}
