---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: usernaut-admin-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: usernaut
  name: usernaut-admin-sa
