---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: usernaut
rules:
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - groups/finalizers
  verbs:
  - update
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - groups/status
  verbs:
  - get
  - patch
  - update
