apiVersion: v1
kind: Secret
metadata:
  name: usernaut-admin-sa-token
  namespace: ddis-asteroid--usernaut
  annotations:
    kubernetes.io/service-account.name: usernaut-admin-sa
type: kubernetes.io/service-account-token
