apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: Group
metadata:
  labels:
    app.kubernetes.io/name: usernaut
    app.kubernetes.io/managed-by: kustomize
  name: test-nested-query
  namespace: usernaut
spec:
  group_name: dataverse-consumer-test-nested
  members:
    ldap_query:
      options:
        include_indirect_reports: true
        include_manager: true
      operator: and                                   # Level 0
      filters:
        - key: employeeType
          criteria: not
          value: "external employee"
      sub_queries:                                    # Level 1
        - operator: or
          filters:
            - key: title
              criteria: contains
              value: engineer
            - key: title
              criteria: contains
              value: developer
        - operator: or
          filters:
            - key: manager
              criteria: equals
              value: mgrAlpha
            - key: manager
              criteria: equals
              value: mgrBeta
          leaf_queries:                               # Level 2
            - operator: and
              filters:
                - key: co
                  criteria: equals
                  value: US
              leaf_sub_queries:                       # Level 3
                - operator: or
                  filters:
                    - key: rhatGeo
                      criteria: equals
                      value: NA
                    - key: rhatGeo
                      criteria: equals
                      value: LATAM
  backends: []
