apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: Group
metadata:
  labels:
    app.kubernetes.io/name: usernaut
    app.kubernetes.io/managed-by: kustomize
  name: test-nested-query
  namespace: usernaut
spec:
  group_name: dataverse-consumer-test-nested
  members:
    ldap_query:
      operator: and
      filters:
        - ldap_query:
            dummy: dummy
            operator: or
            filters:
              - key: title
                criteria: contains
                value: engineer
              - key: title
                criteria: contains
                value: developer
        - ldap_query:
            operator: or
            filters:
              - key: manager
                criteria: equals
                value: pbhattac
                options:
                  include_indirect_reports: true
                  include_manager: false
              - ldap_query:
                  operator: and
                  filters:
                    - key: manager
                      criteria: equals
                      value: rnikhal
                      options:
                        include_indirect_reports: false
                        include_manager: true
                    - ldap_query:
                        operator: or
                        filters:
                          - key: rhatGeo
                            criteria: equals
                            value: nas
                          - key: rhatGeo
                            criteria: equals
                            value: apac
  backends: []
