app:
  name: "usernaut"
  version: "0.0.1"
  environment: "default"

cache:
  driver: "memory"
  inmemory:
    defaultExpiration: -1
    cleanupInterval: -1
  redis:
    host: localhost
    port: "6379"
    database: 0
    password: ""

backends:
- name: fivetran
  type: "fivetran"
  enabled: true
  connection:
    apiKey: apikey
    apiSecret: apisecret
