application:
  name: "usernaut"
  environment: default

cache:
  driver: "memory"
  inmemory:
    defaultExpiration: -1
    cleanupInterval: -1
  redis:
    host: localhost
    port: "6379"
    database: 0
    password: ""

backends:
  fivetran:
    fivetran:
      apiKey: key
      apiSecret: secret
