app:
  name: "usernaut"
  version: "0.0.1"
  environment: "default"

ldap:
  server: "ldap://ldap.test.com:389"
  baseDN: "ou=adhoc,ou=managedGroups,dc=org,dc=com"
  userDN: "uid=%s,ou=users,dc=org,dc=com"
  userSearchFilter: "(objectClass=filterClass)"
  attributes: ["mail", "uid", "cn", "sn", "displayName"]

cache:
  driver: "memory"
  inmemory:
    defaultExpiration: -1
    cleanupInterval: -1
  redis:
    host: localhost
    port: "6379"
    database: 0
    password: ""

backends:
  - name: fivetran
    type: "fivetran"
    enabled: true
    connection:
      apiKey: apikey
      apiSecret: apisecret
