apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ddis-asteroid--config
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    run: redis
status:
  loadBalancer: {}
