name: ci

on: [pull_request] # yamllint disable-line rule:truthy

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read
  checks: write # Used to annotate code in the PR
  pull-requests: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
      - name: go mod tidy check
        run: |
          make mockgen
          echo "Checking go mod tidy"
          go mod tidy
          git diff --exit-code go.mod go.sum
      - name: vendor check
        run: |
          go mod vendor
          git diff --exit-code vendor/
      - name: build
        run: |
          make build
  linting:
    needs: [build]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
      - name: gofmt
        run: |
          gofmt_out=$(gofmt -d $(find * -name '*.go' ! -path 'vendor/*'))
          if [[ -n "$gofmt_out" ]]; then
              failed=1
          fi
          echo "$gofmt_out"
      - name: mockgen
        run: |
          make mockgen
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          install-mode: "goinstall"
          version: v1.64.8
          
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
      - name: tests
        run: |
          make test
